language: ruby
rvm:  
  - "1.9.2"
  - "1.9.3"    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install activesupport -v '4.0.0.rc2' 
before_script:
  - mysql -e 'create database myapp_test;'
env:
  - DB=sqlite
  - DB=mysql
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec